cloudscape-design/board-components

src/board-item/styles.scss
src/internal/drag-handle/icon.tsx
src/internal/resize-handle/icon.tsx

Updates to drag- and resize handles requested from design.
Visual regressions
<details>
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/uti …

Update handles design

---

.github/workflows/build-lint-test.yml

chore: Enable codecov as the repository is now public

---

scripts/themeable-source.js

Current code uses relative imports
https://github.com/cloudscape-design/board-components/blob/6e11de6bdcca12760a814363b23e9c1280d25660/src/board/styles.scss#L1
In order for our theming tool to work, it should be a virtual import `@use 'awsui:tokens'`
Checked the files locally, look as expected
<details>
- _Changes were manually tested for accessibility, see …

chore: Rewrite design tokens import in themeable source

---

scripts/environment.js

Align with what we publish for the main `@cloudscape-design/components` package
https://unpkg.com/browse/@cloudscape-design/components@3.0.236/internal/environment.js
Locally, check that the `/internal/environment.js` file is the same
<details> …

update environment generation

---

.eslintrc
package-lock.json
src/__tests__/base-props-support.test.tsx
src/__tests__/default-props.tsx
src/__tests__/utils.ts
src/board-item/__tests__/board-item-wrapper.tsx
src/board-item/__tests__/board-item.test.tsx
src/board-item/internal.tsx
src/board/internal.tsx
src/internal/base-component/get-data-attributes.ts
src/internal/item-container/index.tsx
src/items-palette/internal.tsx
vite.unit.config.js

Our components should propagate `data-attributes`
Related links, issue #, if available: AWSUI-20970
Copied over tests from the components repository
<details> …

fix: Add support for data-attributes

---

pages/screenshot-area.tsx

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

chore: Fake commit to trigger release

---

package-lock.json
pages/conditional/conditional.page.tsx
test/functional/board-layout/conditional-editing.test.ts

Added a POC that conditional editing is possible
Related links, issue #, if available: AWSUI-20611
Added an e2e test
<details> …

add use-case with conditional edit mode

---

scripts/environment.js

Mirroring the change in the main repo: https://github.com/cloudscape-design/components/pull/1358
Locally. The file is there and the content is expected
<details>
- _If the code handles URLs: all URLs are …

chore: Generate JSON version of the environment file

---

src/board/__tests__/board.test.tsx
src/board/internal.tsx

fix: onItemsChange should call after item get removed

---

src/internal/base-component/use-visual-refresh.ts

The same code has been moved to component toolkit https://github.com/cloudscape-design/component-toolkit/pull/38/files
<details> …

chore: replace with useRuntimeVisualRefresh from component toolkit

---

.github/workflows/release-gh-notes.yml

Add missing workflow
n/a, needs to be merged first
<details>
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/s …

chore: Add release notes workflow

---

package-lock.json
scripts/compile-styles.js

Replace hacky setup with intendend from https://github.com/cloudscape-design/theming-core/pull/72
PR build
<details> …

chore: Use simplified styles build

---

.github/workflows/build-lint-test.yml

Fix our builds
PR build is green
<details>
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/ …

chore: expose CODECOV_TOKEN to the build

---

src/board/__tests__/board-acquisition.test.tsx
src/board/__tests__/board.test.tsx
src/board/__tests__/utils.tsx
src/internal/dnd-controller/__mocks__/controller.ts
src/internal/dnd-controller/controller.ts
src/internal/item-container/__tests__/get-next-droppable.test.ts

Add extra test coverage to make codecov stop complaining about my other changes in #299.
<details> …

chore: Add extra unit test for coverage

---

src/board/internal.tsx
src/board/transition.ts
src/internal/item-container/__tests__/get-next-droppable.test.ts
src/internal/item-container/index.tsx
src/internal/utils/coordinates.ts
src/internal/utils/screen.ts
src/items-palette/internal.tsx

This PR removes the internal direction utility functions and replaces them with the component toolkit.

chore: Replace internal direction utilities with component toolkit.

---

test/functional/board-layout/live-announcements.test.ts

Fix a random failure: https://github.com/cloudscape-design/components/actions/runs/10142866509/job/28043292520
This PR build passes. Visual regression failure is unrelated to my change
<details>
- _If the code …

chore: Fix flaky test

---

src/board/__tests__/board.test.tsx
src/board/internal.tsx

rel: AWSUI-54560
* New unit test securing regression
* Manual testing
<details>
- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check …

fix: Fix error thrown when removing last item

---

.github/workflows/dry-run.yml

Custom dry-run that only builds what is necessary. Re-using the existing dry-run builds a lot more than what is needed and takes the majority of the build time.
<details>
- _If the code handles URLs: all URLs …

chore: Custom dry-run

---

.github/workflows/dry-run.yml

This reverts commit c28a9bd406837ccfd0b44b3e93650288bf3e43b1.
Decided on a new path forward with this: https://github.com/cloudscape-design/actions/pull/63
<details>
- _If the code handles URLs: all URLs are …

chore: Revert "chore: Custom dry-run (#327)"

---

package-lock.json
package.json

chore: Remove design tokens from peer dependencies

---

package-lock.json

Resolving dependabot warning: https://github.com/cloudscape-design/board-components/security/dependabot/45
<details> …

chore: Run npm install

---

.github/workflows/close-stale-issues.yml

There is an issue with that release: https://github.com/cloudscape-design/board-components/actions/runs/14513780982/job/40718200512
Let's go back to the working v6 while they figure proper versioning: https://github.com/aws-actions/stale-issue-cleanup/issues/265
Successful run with v6 from my feature branch: https://github.com/cloudscape-design/board-components/actions/runs/14513991127/job/40718835195
<details> …

chore: downgrade issues workflow

---

package.json
src/__tests__/utils.ts

chore: Ensure LICENSE and NOTICE are copied to lib

---

src/board/internal.tsx
src/board/transition.ts
src/board/utils/__tests__/path.test.ts
src/board/utils/path.ts
src/internal/dnd-controller/controller.ts
src/internal/global-drag-state-styles/index.ts
src/internal/item-container/index.tsx
src/internal/utils/layout.ts
src/items-palette/internal.tsx

The PR removes some of the invariant violations errors that are while meant to spot logical errors in code can occur (and did occur a few times) when there is a race condition.
Rel: AWSUI-61191.
Similar: https://github.com/cloudscape-design/components/pull/3883
<details>
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principle …

refactor: Refactors throwable errors
