.github/workflows/release.yml
package.json
scripts/package-json.js
scripts/themeable-source.js
scripts/utils.js

Create a new utility package, `@cloudscape-design/board-components-themeable` to allow these components to be themed
No theming yet, only publishing the code to our staging CodeArtifact registry
<details>
- …

chore: Create a themeable source

---

pages/grid/permutations.page.tsx
src/board/internal.tsx
src/internal/grid/__tests__/grid.test.tsx
src/internal/grid/grid.tsx
src/internal/grid/interfaces.ts
src/internal/grid/item.tsx
src/internal/grid/styles.scss
test/functional/board-layout/layout.test.ts

Refactor to follow our convention to prefer using scoped class names instead of data-attributes
* PR build
* See the preview deployment
<details>
- _If the code handles URLs: all URLs are validated through …

Remove explicit data attributes

---

src/board/internal.tsx
src/internal/item-container/__tests__/item-container.test.tsx
src/internal/item-container/index.tsx
src/items-palette/__tests__/palette.test.tsx
src/items-palette/internal.tsx

During user interaction the board constantly re-renders and causes items to re-render as well. This leads to performance issues when items have "heavy" content. As we do not expect items to re-render during the user interaction the item content can be cached with an exception of the target item which content might need to adjust when resizing.
Manual checks to ensure the inactive items do not re-render during user interaction.
<details> …

fix: Skip items rendering during user interaction

---

src/board-item/__tests__/board-item-wrapper.tsx
src/board-item/internal.tsx
src/board-item/styles.scss
src/board/__tests__/board.test.tsx
src/internal/drag-handle/index.tsx
src/internal/drag-handle/styles.scss
src/internal/handle/styles.scss
src/internal/item-container/index.tsx
src/internal/resize-handle/index.tsx
src/internal/resize-handle/styles.scss

This change updates the visual affordance of the active focus state for reorder and resize operations. Instead of keeping the focus outline on the reorder or resize handle button, we now display a blue outline around the container to indicate the active reorder/resize operation.
Related links, issue #, if available: AWSUI-20818
<details>
- _Changes were manually tested for accessibility, see …

chore: Update board item focus outline for active state

---

src/board/__tests__/board.test.tsx
src/board/internal.tsx
src/board/transition.ts

While the pointer-based D&D requires position measurements and is exceptionally tricky to test in JSDOM, the keyboard-based operations can be made testable. The current changes makes it possible to test basic keyboard operations for drag- and resize.
<details> …

refactor: Make keyboard transitions for drag- and resize not depend on DOM

---

src/board/interfaces.ts
src/board/internal.tsx
src/board/transition.ts
src/internal/dnd-controller/controller.ts
src/internal/item-container/index.tsx
test/functional/board-layout/keyboard-interactions.test.ts

When the item is not yet inserted the renderItem for it should only be called from the palette, not the board, as it is not yet inserted into the board (the operation can be cancelled). 
Related links, issue #AWSUI-21420
<details>
- _If the code …

fix: Call renderItem in palette when dragging item from palette to board

---

src/internal/item-container/styles.scss

Hide borrowed items instead of dimming. 
Borrowed item – it is an item moved to the board using keyboard (keyboard navigation renders a copy of that item on the board instead). 
Mirroring the mouse drag logic, the item should completely disappear from the origin
Related links, issue #, if available: AWSUI-21437
Locally
<details> …

fix: Hide borrowed items

---

src/internal/item-container/index.tsx
test/functional/board-layout/keyboard-interactions.test.ts

Dragging an item with mouse begins a new transition. If there was another keyboard move in progress (user moved the item with arrow keys but did not press "Enter" to finish the move), it thrown an exception.
The new approach resolves it by forcefully submitting the pending keyboard move.
Related links, issue #, if available: AWSUI-21437
* Locally
* Added new tests
---
P.S. the other, "start using keyboard without releasing mouse" conflict is still possible, but less likely to happen, so I am not going to handle that. At least not until real use-case shows up
<details>
- _Changes are backward-compatible if not indicated, …

fix: Submit keyboard transitions when mouse interactions happen

---

src/board-item/header.tsx
src/board-item/styles.scss

This change is needed  for components [#1317](https://github.com/cloudscape-design/components/pull/1317), which reduces the height of heading elements. This makes it so the handle remains aligned with the container headers
Related links, issue #, if available: [#1317](https://github.com/cloudscape-design/components/pull/1317)
Ran through my dev pipeline
<details>
- _Changes were manually tested for …

chore: Align VR container handle with new header updates

---

pages/with-app-layout/widgets-board.tsx
src/board/__tests__/board.test.tsx
src/board/internal.tsx
src/board/styles.scss
src/internal/global-drag-state-styles/index.ts
src/internal/global-drag-state-styles/styles.scss
src/internal/item-container/__tests__/item-container.test.tsx
src/internal/item-container/index.tsx
src/internal/item-container/styles.scss
src/internal/utils/use-auto-scroll.ts
src/test-utils/dom/board/index.ts
test/functional/board-layout/layout.test.ts

Self explanatory. Refactored to use portals for currently dragged item
Related links, issue #, if available: AWSUI-21442
* PR build
* Added a unit test to check when portal is activated
* The exact overlap issues are hard to test automatically (requires flaky screenshot test)
<details> …

fix: Render dragged item using portals to prevent z-index issues

---

src/board/__tests__/board.test.tsx
src/board/utils/events.ts

fix that removedItem is always null in onItemChange event detail.
<details> …

fix: removedItem in onItemChange event detail is always null

---

pages/dnd/items.tsx
src/internal/item-container/__tests__/item-container.test.tsx
src/internal/item-container/index.tsx
test/functional/board-layout/item-actions.test.ts
test/functional/board-layout/layout.test.ts

The previous fix for preventing z-index issues (https://github.com/cloudscape-design/board-components/pull/258) introduced an unexpected regression:
- when reordering a board item, this would re-mount, losing its internal state or re-firing API calls. This was due to it being rendered in a React Portal while being re-ordered (to avoid the aforementioned z-index issues).
After some investigation, I concluded the original z-index issues raised by customers where not happening while reordering the items, instead they were happening only when inserting them from the palette to the board.
With this fix, we no longer render the items in Portals while being reordered (but still keep this functionality when inserting them), which seems a fair compromise given that widgets on the items palette …

chore: Don't render items in portals when reordering

---

pages/micro-frontend/integration.page.tsx

When "micro-frontends" and mounted but never un-mounted the proper cleanup does not happen. As result when using React portals those are rendered multiple times instead of one.
Manual testing, see below.
Before:
https://github.com/cloudscape-design/board-components/assets/20790937/a0cf8d37-f802-4f2b-819b-d48eeb235c1d
After:
https://github.com/cloudscape-design/board-components/assets/20790937/13ab72d2-5b0b-4fe9-9fe2-abd59fcb7351
<details> …

fix: Unmount nodes on cleanup in micro-frontend integration page

---

test/functional/board-layout/live-announcements.test.ts

The delay in the test suite for item removal announcements is exactly the same as the code delay to trigger the announcement. The proximity of the delays might be the cause of the observed dry-run flakiness of this test.
Runned integ test suite several times in a row to ensure stability
<details> …

chore: Try fix remove-item test flakiness

---

.github/workflows/build-lint-test.yml
.github/workflows/dry-run.yml
.github/workflows/release.yml
.github/workflows/visual-regression.yml

This PR switches to the new shared repository for GitHub workflows and actions: https://github.com/cloudscape-design/actions.
For the most recent changes to the shared workflows, see https://github.com/cloudscape-design/actions/pull/1. The new configuration was successfully tested in this Draft PR: https://github.com/cloudscape-design/components/pull/1672.
<details> …

chore: Switch to new actions repo for workflows

---

src/board-item/styles.scss
src/internal/drag-handle/styles.scss
src/internal/resize-handle/styles.scss
src/internal/shared.scss
test/visual/drag-states.test.ts

A past commit moved focus rings to the container level when the container was being moved or resized via keyboard, but also took them out when the buttons themselves were focused, which is incorrect.
Related links, issue #, if available: AWSUI-23006
It looks like every time I re-run screenshot tests, there’s different flaky screenshots each time. Looking at past PRs, this commit might not be the one that introduces the flakiness, but it does add new tests that are expected to fail (because they didn't exist before).
<details>
- _Changes are backward-compatible if not indicated, see …

fix: Restore styled focus rings to drag and resize handles

---

.eslintrc
pages/conditional/conditional.page.tsx
pages/dnd/commons.tsx
pages/dnd/engine-query-test.page.tsx
pages/dnd/events-table.tsx
pages/dnd/items.tsx
pages/dnd/update-layout-test.page.tsx
pages/grid/with-widget-containers-compact.page.tsx
pages/grid/with-widget-containers.page.tsx
pages/micro-frontend/integration.page.tsx
pages/widget-container/permutations.page.tsx
pages/with-app-layout/app-layout.tsx
pages/with-app-layout/delete-confirmation-modal.tsx
pages/with-app-layout/widgets-board.tsx
pages/with-app-layout/widgets-palette.tsx
src/board-item/__tests__/board-item.test.tsx
src/board/__tests__/board.test.tsx
src/internal/drag-handle/index.tsx
src/internal/resize-handle/index.tsx

Subpath imports should be preferred, because they allow for better bundle size optimizations
Updated eslint config to validate imports in the future
<details>
- _If the code handles URLs: all URLs are …

feat: replace @cloudscape-design/components with subpath imports

---

pages/app/page.tsx
pages/dnd/engine-page-template.tsx
pages/widget-container/permutations.page.tsx
pages/with-app-layout/widgets-board.tsx
src/board-item/styles.scss
src/board/internal.tsx
src/board/styles.scss
src/board/transition.ts
src/internal/global-drag-state-styles/styles.scss
src/internal/grid/grid.tsx
src/internal/grid/interfaces.ts
src/internal/handle/styles.scss
src/internal/item-container/__tests__/get-next-droppable.test.ts
src/internal/item-container/__tests__/item-container.test.tsx
src/internal/item-container/get-next-droppable.ts
src/internal/item-container/index.tsx
src/internal/item-container/styles.scss
src/internal/resize-handle/styles.scss
src/internal/screenreader-grid-navigation/styles.scss
src/internal/screenreader-only/styles.scss
src/internal/shared.scss
src/internal/utils/__tests__/rects.test.ts
src/internal/utils/coordinates.ts
src/internal/utils/rects.ts
src/internal/utils/screen.ts
src/items-palette/internal.tsx

Support for RTL
Observations:
* Settings button dropdown opens to the left when direction="rtl";
* Pressing arrow left when the palette is open causes screen to grow;
* Need to invert the resize icon and cursor.
https://github.com/cloudscape-design/board-components/assets/20790937/b9f645b2-bcf3-4caa-9b49-339f88b8375a
<details> …

chore: RTL support for keyboard commands and pointer events

---

vite.config.e2e-functional.mjs

As in https://github.com/cloudscape-design/browser-test-tools/pull/84, to prevent Chromedriver from becoming unresponsive.
*Issue #* `AWSUI-46673`
Dry-run passed 3 times consecutively: https://github.com/cloudscape-design/board-components/actions/runs/9548127966/job/26318958743?pr=304
Visual regression tests fail because it compares against image snapshot of the previous commit (see logic [here](https://github.com/cloudscape-design/board-components/blob/main/.github/workflows/visual-regression.yml)) and the previous snapshot still has the dark header which was recently removed from the app layout. After merging this PR the snapshots should automatically be updated according to the `update` workflow.
<details>
_The following items are to be evaluated by …

chore: Limit tests concurrency

---

pages/dnd/engine-a2p-test-async.page.tsx
pages/dnd/engine-page-template.tsx
src/board/internal.tsx
test/functional/board-layout/item-actions.test.ts

In case consumers executed the `actions.removeItem()` and implemented the items update logic inside the `onItemsChange` in async mode the focus gets lost because in our code we always assume that after the `removeItem` exection the items will be updated.
This code fixes that by not depending on a use effect and just immediately focuses the next item.
issues/AWSUI-47888
Added a functional test and a new page with the async behavior simulation (using `setTimeout()`.
<details>
- _Changes do not include unsupported …

chore: Focus immediately when remove transition starts

---

.stylelintrc
build-tools/stylelint/index.js
build-tools/stylelint/license-headers.js
build-tools/stylelint/package.json
package-lock.json
package.json
pages/app/page-layout.module.css
pages/app/test-bed.module.css
pages/canvas/layouts.module.css
pages/dnd/engine.module.css
pages/grid/permutations.module.css
src/board-item/styles.scss
src/board/styles.scss
src/internal/drag-handle/styles.scss
src/internal/global-drag-state-styles/styles.scss
src/internal/grid/styles.scss
src/internal/handle/styles.scss
src/internal/item-container/styles.scss
src/internal/resize-handle/styles.scss
src/internal/shared.scss
src/items-palette/styles.scss

- Add stylelint dependency
- Add custom Cloudscape stylelint plugin
- Run lint against repository
This code is basically technical debt on arrival. These linting rules will get moved into a shared package in the future but since we do not have an ETA for that we should still have a good process to ensure our files are linted consistently.
<details>
- _Changes …

chore: Add stylelint

---

src/board/__tests__/board-acquisition.test.tsx
src/board/internal.tsx

When acquiring item with keyboard the focus can get lost upon submission due to rendering function change. The new refocusing logic mitigates that.
Rel: AWSUI-54391
* New unit test that secures the regression
* Manually tested with demos
<details>
- …

fix: Fix drag handle focus after item acquisition

---

src/board-item/__tests__/board-item.test.tsx
src/test-utils/dom/board-item/index.ts

Board item has slots and those must return ElementWrapper and not ContentWrapper so that it is possible to chain selectors like `createWrapper().findBoardItem().findContent().findButton()`. That requires respective components selectors to be imported e.g. `import "@cloudscape-design/components/test-utils/dom"` or `import "@cloudscape-design/code-view/test-utils/dom"`.
* New unit tests
<details>
- …

fix: Makes board item test utils wrappers chainable

---

.github/workflows/visual-regression.yml

Update actions node version to explicitly node version 20 as node 18 is out of active support.
AWSUI-59859
PR check runs the action. It doesn't pass successfully ...but it runs 🤷🏻‍♂️
<details>
- _If the code …

chore: Upgrade visual resgression script to node 20

---

test/functional/board-layout/layout.test.ts

We want to show scrollbars in tests but one test in board-components fails when doing that ([dry-run](https://github.com/cloudscape-design/browser-test-tools/actions/runs/11796000980/job/32868652896?pr=120)). This is because as the element is dragged, grid placeholders are added below, which causes a scrollbar to appear and the page content slightly moves to the left. Then, the test, which compares the dragged element's position against the placeholders, does not find it exactly where it expects.
I don't think this is really a bug, rather expected behavior given how browsers work. Therefore fixing in the test.
Used [this approach](https://github.com/cloudscape-design/components/pull/3002/files#diff-596d348eb0961ab3457c7941e2c60330639c21a43f1e2e96d3759016adb58eea) to show scrollbars …

chore: Make window taller in test to avoid scrollbars

---

src/items-palette/internal.tsx

Introduces column layout to board items palette to fit more items when there is enough horizontal space in both side and bottom orientations of the panel.
Rel: [4xTcAv3PK6h2]
* Manual testing in test pages and demos
<details>
- _If the code handles …

feat: Use column layout in items palette

---

package-lock.json
scripts/test-utils.js
src/__tests__/__snapshots__/test-utils-wrappers.test.tsx.snap

We moved the test utils generation code to the `test-utils` repo [here](https://github.com/cloudscape-design/test-utils/pull/77). This PR removes the redundant code and reuses the utils exported from the `test-utils` repo.
No functional changes are expected. The snapshot diffs must be only spacings/ordering.
Similar to: https://github.com/cloudscape-design/chat-components/pull/35, https://github.com/cloudscape-design/code-view/pull/54, https://github.com/cloudscape-design/components/pull/3087
We have already implemented functional tests both in the `test-utils` repo and `components` repo which generates actual test utils and tries to query dom with the generated test utils.
- Unit tests for test utils.
- Unit tests for components.
- …

chore: Replaces the test utils script with centralized one

---

.github/workflows/visual-regression.yml
pages/dnd/engine-page-template.tsx

Upgrade upload-artifact to v4 because https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
<details>
- _If the code handles URLs: all URLs are validated through [the …

chore: Upgrade upload-artifact to v4

---

pages/shared/i18n.ts

Add instructions to temp disable keyboard navigation while resizing/moving.
Why? A screen reader's keyboard navigation mode may intercept arrow key presses. We can't disable that with an appropriate role, that's why we extend the drag handlers description with that information.
Updated copy got approved, see CR-180476213.
Related links, issue #, if available: 
- CR-180476213
- AWSUI-60203
- verified updated description on VoiceOver
<details> …

chore: Update board item's i18n strings

---

package-lock.json
package.json
src/internal/utils/__tests__/throttle.test.ts

- Upgrades vite, vitest, @vitest/coverage-v8 and @vitejs/plugin-react to latest available versions
- Updates unit test to use new `MockInstance` interface which replaced the now removed `SpyInstance`
- Existing tests
- Downloaded and locally reviewed the generated screenshots
<details> …

chore: Upgrade vite-related dependencies

---

src/internal/base-component/use-telemetry.ts
src/internal/utils/__tests__/get-visual-theme.test.ts
src/internal/utils/get-visual-theme.ts

Ports over helper function from https://github.com/cloudscape-design/components/pull/3355
- Copied over unit tests
- _Changes are covered …

chore: Extract common visual theme code into helper function

---

src/internal/item-container/index.tsx
test/functional/board-layout/regressions.test.ts

We have two drastically different types of d&d transition: pointer-based and keyboard-based. Due to async nature of events, there was a bug where the pointer-based transition crashed when user pressed Escape. It happened because:
1. User starts pointer-based d&d transition (moves or resizes an item, but w/o commit);
2. User presses Escape (or Space, Enter) - the keyboard handler submits/discards the transition;
3. User moves cursor a little - the onPointerMove handler is still there, it attempts to update the transition that no longer exists, which leads to a crash.
Besides, pressing arrow keys while the pointer-based transition was in progress led to unexpected results, too. The solution is to disallow keyboard input while pointer-based d&d is engaged by immediately cancelling the …

fix: Fixes a bug when pointer d&d transition crashes when pressing Escape
